### PR TITLE
#68: account for output transform

### LINKED ISSUE #68: wl-screenrec doesn't take into account monitor rotation when using slurp
When using slurp to get the geometry of what to record, my second monitor that stands vertically is recorded horizontally. Everything is sideways. This also affects the position of where stuff is recorded on my main monitor, which is not rotated. My second monitor is 2560x1440 and rotated, so when I select something on my main monitor, instead of using 1440 to get the offset, it uses 2560 it seems.

https://github.com/russelltg/wl-screenrec/assets/6963524/6dc3cc08-39e7-481f-bd0e-b4cc19248e41

How wl-screenrec sees my rotated monitor. The offset for my main monitor would be 1440, since my second monitor is to the left of my main monitor. When I select something on my main monitor, the offset is wrong and it ends up recording some other region of my main monitor which wasn't what I selected.

Relevant part of my script
```bash
_slurp=$(slurp)
wl-screenrec \
	-g "$_slurp" \
	--audio \
	-f "$_file$_videocontainer"
```

To record my main monitor, I've instead just made my script record the output instead of selecting geometry. 

```bash
wl-screenrec \
	-o DP-1 \
	--audio \
	--audio-device "$_aOutput" \
	-f "$_file$_videocontainer"
```

This ensures I at least end up recording the thing I want to record, but it would be nice if I could simply select it instead.

### PR DESCRIPTION
**Pull request by russelltg**
Fixes #68

This was all surprisingly complicated, ha! @Andeskjerf can you test and confirm? Tested locally with all transforms

### CODE REVIEW

**Comment by Andeskjerf** [comment]
Recording my main monitor now works without problem when using slurp :) Thank you!

However, trying to record my rotated monitor fails. I tried both with and without hardware encoding, both failing with different errors.

Hardware
```
Opening libva device from DRM device /dev/dri/renderD128
[Parsed_transpose_vaapi_2 @ 0x59418cf6e1c0] VAAPI driver doesn't support transpose
[Parsed_transpose_vaapi_2 @ 0x59418cf6e1c0] Failed to configure output pad on Parsed_transpose_vaapi_2
thread 'main' panicked at src/main.rs:1762:18:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(22: Invalid argument)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: <wl_screenrec::State as wayland_client::event_queue::Dispatch<wayland_protocols_wlr::screencopy::v1::generated::client::zwlr_screencopy_frame_v1::ZwlrScreencopyFrameV1,()>>::event
   4: wayland_client::event_queue::queue_callback
   5: wayland_client::event_queue::EventQueue<State>::dispatching_impl
   6: wayland_client::event_queue::EventQueue<State>::blocking_dispatch
   7: wl_screenrec::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Software
```
Opening libva device from DRM device /dev/dri/renderD128
[Parsed_scale_vaapi_1 @ 0x64d2f9976000] Hardware does not support output format yuv420p.
[Parsed_scale_vaapi_1 @ 0x64d2f9976000] Failed to configure output pad on Parsed_scale_vaapi_1
thread 'main' panicked at src/main.rs:1762:18:
called `Result::unwrap()` on an `Err` value: ffmpeg::Error(22: Invalid argument)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: <wl_screenrec::State as wayland_client::event_queue::Dispatch<wayland_protocols_wlr::screencopy::v1::generated::client::zwlr_screencopy_frame_v1::ZwlrScreencopyFrameV1,()>>::event
   4: wayland_client::event_queue::queue_callback
   5: wayland_client::event_queue::EventQueue<State>::dispatching_impl
   6: wayland_client::event_queue::EventQueue<State>::blocking_dispatch
   7: wl_screenrec::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I also tried using `-o` to record my monitors, and this fails for the transformed monitor. The errors appear identical to the above.

For reference, I use a RX 6800 XT with mesa drivers.

**Comment by russelltg** [comment]
Ah, darn...
```
VAAPI driver doesn't support transpose
```

I'll need to look at other ways to do this. Maybe vulkan or something...

**Comment by rj1** [comment]
can confirm I am experiencing this exact issue as well

**Comment by svenstaro** [comment]
I'm still getting `VAAPI driver doesn't support transpose` on my Radeon 780M. Shouldn't that particular issue still be tracked?

Funnily enough, it also crashes with `--no-hw`:
```
wl-screenrec --no-hw -o DP-6 -f lol.mkv
Opening libva device from DRM device /dev/dri/renderD128
[Parsed_scale_vaapi_1 @ 0x5eb38a66e740] Hardware does not support output format yuv420p.
[Parsed_scale_vaapi_1 @ 0x5eb38a66e740] Failed to configure output pad on Parsed_scale_vaapi_1
```

**Comment by russelltg** [comment]
Yeah, `--no-hw` only disables HW encoding, not HW scale/flip/pixel format conversion. 

For output transform on radv, I think the best best is wait for the vulkan support. Would be curious to have someone test that (See #90). I still need to add transform support to that PR, but would be interesting to see if it works on radv with no transform

**Comment by svenstaro** [comment]
Sure, will get right on that. Can we chat somewhere real time (Discord, Matrix) for debugging, multiple stabs at this, etc?

**Pull request merged**
